### ISSUE TITLE
libintl load error with macOS Sierra (10.12.3) 

### ISSUE THREAD

**Issue by Dalar** [asciidoctor/asciidoctor-mathematical#26]
```
$ asciidoctor-pdf -r asciidoctor-mathematical -o test.pdf sample.adoc --trace
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/mathematical-1.6.7/lib/mathematical/mathematical.bundle, 9): Library not loaded: @rpath/libintl.9.dylib (LoadError)
  Referenced from: /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/mathematical-1.6.7/ext/mathematical/lasem/build/liblasem.dylib
  Reason: image not found - /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/mathematical-1.6.7/lib/mathematical/mathematical.bundle
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/mathematical-1.6.7/lib/mathematical.rb:1:in `<top (required)>'
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/asciidoctor-mathematical-0.2.2/lib/asciidoctor-mathematical/extension.rb:23:in `process'
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:479:in `[]'
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:479:in `block in parse'
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:478:in `each'
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:478:in `parse'
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.5/lib/asciidoctor.rb:1347:in `load'
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.5/lib/asciidoctor.rb:1465:in `convert'
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:95:in `block in invoke!'
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:87:in `each'
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:87:in `invoke!'
	from /Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/asciidoctor-pdf-1.5.0.alpha.14/bin/asciidoctor-pdf:31:in `<top (required)>'
	from /Users/amodig/.rbenv/versions/2.4.0/bin/asciidoctor-pdf:22:in `load'
	from /Users/amodig/.rbenv/versions/2.4.0/bin/asciidoctor-pdf:22:in `<main>'
```
I noticed that `libintl.9.dylib` isn't installed on my system (see `find` below). With Homebrew, `libintl` comes with `gettext`, which I linked, but it has only `libint.8.dylib`.
```
$ sudo find /usr/ -name *libintl*
/usr/local/Cellar/gettext/0.19.8.1/include/libintl.h
/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.8.dylib
/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.a
/usr/local/Cellar/gettext/0.19.8.1/lib/libintl.dylib
/usr/local/Cellar/gettext/0.19.8.1/share/gettext/intl/libintl.rc
/usr/local/Cellar/texi2html/5.0/share/texi2html/lib/libintl-perl
/usr/local/include/libintl.h
/usr/local/lib/libintl.8.dylib
/usr/local/lib/libintl.a
/usr/local/lib/libintl.dylib
/usr/local/lib/libintl.la
/usr/local/share/doc/libintl
```

I tested `mathematical` separately, and it works. I have brew+rbenv installation of ruby 2.4.0 (https://github.com/rbenv/rbenv#homebrew-on-mac-os-x).

Maybe a similar problem here:
http://stackoverflow.com/questions/42080325/rp2-missing-libintl-9-dylib-library

**Comment by ProgramFan** [comment]
Can you try to reinstall mathematical and check if it works? I suspect the load error is caused by incorrect installation.

```bash
gem uninstall mathematical
gem install mathematical
```

**Comment by jazzyearrings** [comment]
You should install the latest version of gettext; it solved my problem on osx

`conda install -c anaconda gettext=0.19.8`

**Comment by amodig** [comment]
Re-installing both gettext and mathematical helped! Thank you.

I got a new issue, the equations in tables or titles don't work. Can you give me quick help or should I open a new issue?

I get the following warnings:
```
$ asciidoctor-pdf -r asciidoctor-mathematical -o test.pdf sample.adoc --trace --verbose
asciidoctor: WARNING: conversion missing in backend pdf for stem
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ttfunk-1.4.0/lib/ttfunk/table.rb:25: warning: instance variable @offset not initialized
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ttfunk-1.4.0/lib/ttfunk/table.rb:25: warning: instance variable @offset not initialized
asciidoctor: WARNING: conversion missing in backend pdf for stem
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ttfunk-1.4.0/lib/ttfunk/table.rb:25: warning: instance variable @offset not initialized
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ttfunk-1.4.0/lib/ttfunk/table.rb:25: warning: instance variable @offset not initialized
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ttfunk-1.4.0/lib/ttfunk/table.rb:25: warning: instance variable @offset not initialized
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/prawn-2.1.0/lib/prawn/font/ttf.rb:117: warning: instance variable @italic_angle not initialized
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ttfunk-1.4.0/lib/ttfunk/table.rb:25: warning: instance variable @offset not initialized
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ttfunk-1.4.0/lib/ttfunk/table.rb:25: warning: instance variable @offset not initialized
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ttfunk-1.4.0/lib/ttfunk/table.rb:25: warning: instance variable @offset not initialized
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/prawn-2.1.0/lib/prawn/font/ttf.rb:117: warning: instance variable @italic_angle not initialized
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ttfunk-1.4.0/lib/ttfunk/table.rb:25: warning: instance variable @offset not initialized
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ttfunk-1.4.0/lib/ttfunk/table.rb:25: warning: instance variable @offset not initialized
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/ttfunk-1.4.0/lib/ttfunk/table.rb:25: warning: instance variable @offset not initialized
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/prawn-2.1.0/lib/prawn/font/ttf.rb:117: warning: instance variable @italic_angle not initialized
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/prawn-2.1.0/lib/prawn/font/ttf.rb:117: warning: instance variable @italic_angle not initialized
/Users/amodig/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/prawn-2.1.0/lib/prawn/font/ttf.rb:117: warning: instance variable @italic_angle not initialized
```

**Comment by jazzyearrings** [comment]
I just found out actually I intended to answer the post [http://stackoverflow.com/questions/42080325/rp2-missing-libintl-9-dylib-library](url) which tried to install R with ananconda but failed to link to libintl.9.dylib. Sorry but I know nothing about Asciidoctor.

**Comment by ProgramFan** [comment]
It is better to open a new issue, @amodig. Equations in tables and titles does not work for the published gem, but shall work for the latest trunk, and with latest asciidoctor-pdf if you use asciidoctor-pdf. You can read the commit messages and find it out.

**Comment by ProgramFan** [comment]
Never matters, @jazzyearrings. You can delete the post if you want. 😄
